spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver  # Menambahkan driver class untuk JDBC

  jpa:
    hibernate:
      ddl-auto: update  # Mengatur Hibernate untuk memperbarui skema tanpa menghapus data
    show-sql: true       # Menampilkan SQL yang dieksekusi oleh Hibernate di log
    properties:
      hibernate:
        format_sql: true  # Memformat output SQL agar lebih mudah dibaca
    open-in-view: false   # Disarankan untuk menghindari LazyInitializationException

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081
